services:
  web:
    build: ./
    command: ./music-lib-go
    env_file:
      - .env
    environment:
      - ENV=production
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5439:5432

  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s