services:
  web:
    image: mdmitrym/music-lib-go:latest
    env_file:
      - .env
    environment:
      - ENV=production
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  db:
    image: postgres:latest
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

  redis:
    image: redis
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s