previews:
  generation: automatic # Enable preview environments

services:
  - type: web
    name: go-server
    env: docker
    image:
      url: docker.io/mdmitrym/music-lib-go # Укажите ваш образ
    plan: free # Выберите подходящий тарифный план
    envVars:
      - key: DATABASE_URL
        fromDatabase: 
          name: go-db # Ссылка на базу данных PostgreSQL
          property: connectionString

databases:
  - name: go-db
    databaseName: postgres
    user: postgres
    plan: free # Бесплатный план для PostgreSQL