port: ":8080"

#prod db from docker-compose
db:  
  host: "db" #from docker compose
  port: "5432"

#for local development
dev_db:
  host: "localhost"
  port: "5439"
  
redis:
  host: "redis"
  port: "6379"
  DB: 0

redis_dev:
  host: "localhost"
  port: "6380"
  DB: 0