port: ":8080"

#prod db from docker-compose
db:
  username: "postgres"
  host: "db" #from docker compose
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

#for local development
dev_db:
  username: "postgres"
  host: "localhost"
  port: "5439"
  dbname: "postgres"
  sslmode: "disable"

redis:
  host: "redis"
  port: "6379"
  DB: 0

redis_dev:
  host: "localhost"
  port: "6380"
  DB: 0